# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Native Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build fat jar with maven
      run: mvn -B clean package
    - name: Build native app with maven
      run: mvn -B package -Pnative
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "0.2.0"
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: "List target directory"
      run: echo ${{ steps.create_release.outputs.upload_url }}
    - name: "List 2"
      run: echo ${ steps.create_release.outputs.upload_url }
    - uses: dev-drprasad/delete-tag-and-release@v0.2.0
      name: Delete the previous release
      with:
        delete_release: true
        tag_name: "0.1.0"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/quarkus-wrk-runner
          target/quarkus-wrk-runner.jar
        tag_name: "0.1.0"
        prerelease: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}