# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Native Application (All Versions)

on:
  workflow_dispatch:

jobs:
  linux-jdk17-mandrel-x64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        name: Delete the previous release
        with:
          delete_release: true
          tag_name: "0.1.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "0.1.0"
          release_name: Release 0.1.0
          draft: true
          prerelease: true
      - name: Push upload url to file
        run: echo "${{ steps.create_release.outputs.upload_url }}" > upload_url.txt
      - name: Upload upload_url artifact
        uses: actions/upload-artifact@v1
        with:
          name: upload_url.txt
          path: upload_url.txt
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build fat jar with maven
        run: mvn -B clean package
      - name: Build native app with maven
        run: mvn -B package -Pnative -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.3.0.0-Final-java17
      - name: Set Upload URL to Environment Variable
        run: echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV
      - name: Upload Release Asset (Linux binary)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: target/quarkus-wrk-runner
          asset_name: quarkus-wrk-linux-64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset (Fat Jar)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: target/quarkus-wrk-runner.jar
          asset_name: quarkus-wrk-runner.jar
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows-amd64:
    runs-on: windows-2019
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup GraalVM'
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.3.0'
          java: 'java17'
          arch: 'amd64'
          personal-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Install native-image'
        run: gu.cmd install native-image
      - name: 'Print Info'
        run: java -version && gu.cmd list -v && mvn --version && pwd
      - name: 'Build Image (windows)'
        shell: cmd
        run: call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat" && mvn --batch-mode -Pnative clean package
      - name: Download upload_url artifact
        uses: actions/download-artifact@v1
        with:
          name: upload_url.txt
      - name: Get upload_url
        run: |
          export upload_url=$(<upload_url.txt)
          rm upload_url.txt
          echo "upload_url=${upload_url}" >> $GITHUB_ENV
      - name: Upload Release Asset (Windows exe)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: target/quarkus-wrk-runner.exe
          asset_name: quarkus-wrk.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
